_target_: src.models.token_classification_module.TokenClassificationModule
num_classes: ${data.num_classes}
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.pre_trained_llm.ModelFromConfig
  model_name: 'xlm-roberta-base'
  num_classes: ${data.num_classes}